M48
; DRILL file {KiCad 9.0.2} date 2026-01-18T17:28:18-0600
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2026-01-18T17:28:18-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.2
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0709
%
G90
G05
T1
X2.4348Y-1.8055
X2.6258Y-1.8055
T2
X2.423Y-1.6862
X2.6376Y-1.6862
M30
